import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

const gtfonts = localFont({
  src: [
    {
      path: '../../public/fonts/GT-Walsheim-Regular-Trial.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-gt',
});

export const metadata: Metadata = {
  title: 'Dimension Test',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${gtfonts.variable} font-gt`}>
      <body>{children}</body>
    </html>
  );
}
