import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import localFont from '@next/font/local';

const inter = Inter({ subsets: ['latin'] });
const gtfonts = localFont({
  src: [
    {
      path: '../../public/fonts/GT-Walsheim-Regular-Trial.woff2',
      weight: '500',
      style: 'normal',
    },
    // {
    //   path: '../../public/fonts/GT-Walsheim-Bold-Oblique-Trial.woff2',
    //   weight: '700'
    // }
  ],
  variable: '--font-gt',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${gtfonts.variable} font-gt`}>
      <body>{children}</body>
    </html>
  );
}
